/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddMemberModal: typeof import('./src/components/AddMemberModal.vue')['default']
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    DataDisplay: typeof import('./src/components/DataDisplay.vue')['default']
    DeleteDialog: typeof import('./src/components/DeleteDialog.vue')['default']
    EditMemberDialog: typeof import('./src/components/EditMemberDialog.vue')['default']
    NoDataAlert: typeof import('./src/components/NoDataAlert.vue')['default']
  }
}
